# Generated by Django 3.2.2 on 2021-05-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dgmail', models.EmailField(max_length=100)),
                ('ugmail', models.EmailField(max_length=100)),
                ('pid', models.IntegerField()),
                ('size', models.CharField(max_length=100)),
                ('chestsize', models.IntegerField()),
                ('waistsize', models.IntegerField()),
                ('sleevelength', models.CharField(max_length=100)),
                ('shoulderlength', models.IntegerField()),
                ('neckdepth', models.IntegerField()),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('adress', models.TextField(max_length=255)),
                ('phoneno', models.IntegerField()),
                ('cardtype', models.CharField(choices=[('Debitcard', 'Debitcard'), ('creditcard', 'creditcard')], max_length=100)),
                ('cardno', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
            options={
                'db_table': 'opayment',
            },
        ),
    ]
