# Generated by Django 3.2.2 on 2021-05-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='adress',
            field=models.TextField(max_length=100),
        ),
    ]
