# Generated by Django 3.2.2 on 2021-05-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dregister',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('mobileno', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('imagefile', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'dregister',
            },
        ),
    ]
