# Generated by Django 3.2.2 on 2021-05-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_designs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designs',
            old_name='type',
            new_name='designtype',
        ),
    ]
