# Generated by Django 3.2.2 on 2021-05-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_rename_type_designs_designtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designs',
            name='design',
            field=models.ImageField(upload_to='designs/'),
        ),
    ]
