# Generated by Django 3.2.2 on 2021-05-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_alter_designs_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='DesignName',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
