# Generated by Django 3.2.2 on 2021-05-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0005_designs_designname'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='description',
            field=models.TextField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='designs',
            name='price',
            field=models.IntegerField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='designtype',
            field=models.CharField(choices=[('partywear', 'partywear'), ('traditional', 'traditional')], default='NULL', max_length=100),
        ),
    ]
