# Generated by Django 3.2.2 on 2021-05-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0007_alter_designs_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designs',
            name='description',
        ),
    ]
