# Generated by Django 3.2.2 on 2021-05-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0008_remove_designs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='description',
            field=models.TextField(default='NULL', max_length=200),
        ),
    ]
