# Generated by Django 3.2.2 on 2021-05-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0012_remove_designs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='description',
            field=models.TextField(default=10, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designs',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
