# Generated by Django 3.2.2 on 2021-05-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0014_alter_designs_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designs',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
