# Generated by Django 3.2.2 on 2021-05-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0017_auto_20210516_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designs',
            name='description',
        ),
        migrations.RemoveField(
            model_name='designs',
            name='price',
        ),
    ]
