# Generated by Django 3.2.2 on 2021-05-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0018_auto_20210516_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
