# Generated by Django 3.2.2 on 2021-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0019_designs_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='description',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
