# Generated by Django 3.2.2 on 2021-05-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uregister',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('mobileno', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'uregister',
            },
        ),
    ]
