# Generated by Django 3.2.2 on 2021-05-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.EmailField(max_length=100)),
                ('pid', models.IntegerField()),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=100)),
                ('chestsize', models.IntegerField()),
                ('waistsize', models.IntegerField()),
                ('sleevelength', models.CharField(choices=[('sleeveless', 'sleeveless'), ('halfsleeves', 'halfsleeves'), ('fullsleeves', 'fullsleeves'), ('petalsleeves', 'petalsleeves')], max_length=100)),
                ('shoulderlength', models.IntegerField()),
                ('neckdepth', models.IntegerField()),
            ],
            options={
                'db_table': 'bag',
            },
        ),
    ]
